//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCDataBaseInterFace.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_MFCDATABASEINTERFACE_DIALOG 102
#define IDD_AUTH                        102
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        130
#define IDR_MENU_MAIN                   132
#define IDD_EXPORT                      133
#define IDD_PROCEDURES                  138
#define IDD_DIALOG2                     139
#define IDD_FUNCTIONS                   139
#define IDD_ABOUT                       142
#define IDD_NEWDB                       144
#define IDD_TABLES                      146
#define IDD_QUERY                       148
#define IDD_DIALOG3                     149
#define IDD_RESULT                      149
#define IDD_HOME                        152
#define IDD_VARIABLES                   154
#define IDD_CHARSETS                    156
#define IDD_DATABASES                   158
#define IDD_CHANGEUSRPWD                161
#define IDD_CHANGEVARVALUE              163
#define IDD_STATUS                      165
#define IDD_STATUS_SERVER               165
#define IDD_STATUS_PROCESSES            167
#define IDD_STATUS_QSTATS               169
#define IDD_DIALOG1                     170
#define IDD_STATUS_MONITOR              170
#define IDB_BITMAP1                     173
#define IDB_PNG1                        174
#define IDB_PNG2                        175
#define IDR_IMAGE1                      176
#define IDB_PNG3                        177
#define IDB_PNG4                        178
#define IDB_PNG5                        179
#define IDD_PLUGINS                     180
#define IDD_ENGINES                     181
#define IDD_LOADING                     185
#define IDD_HOME_RUS                    189
#define IDD_PENDULUM                    191
#define IDD_TABLE_STRUCTURE             193
#define IDD_TABLE_RECORDS               194
#define IDD_RESULT1                     195
#define IDD_RESULT_SHORT                195
#define IDB_PNG6                        197
#define IDB_PNG_LOADING                 197
#define IDD_HOTKEYS_HINTS               198
#define IDD_HYSTORY                     200
#define IDB_BITMAP2                     202
#define IDB_BITMAP3                     203
#define IDB_BITMAP4                     204
#define IDB_BITMAP5                     205
#define IDB_BITMAP6                     206
#define IDB_BITMAP7                     207
#define IDB_BITMAP8                     208
#define IDD_QUERY_RUS                   209
#define IDC_EDIT1                       1000
#define IDC_EDT_OUTQTEXT                1000
#define IDC_EDIT_DESCRIPTION            1000
#define IDC_EDIT_CURRENTPAGE            1000
#define IDC_EDIT_DBNAME                 1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_QTEXT                  1001
#define IDC_FILTER_DATABASES            1001
#define IDC_EDIT_ENTERPASSWORD          1001
#define IDC_BTN_CONNECT                 1002
#define IDC_BTN_EXIT                    1003
#define IDC_LIST1                       1004
#define IDC_COMBO1                      1005
#define IDC_SEL_TABLE                   1005
#define IDC_COMBO_CHARSET               1005
#define IDC_COLLATION                   1005
#define IDC_TAB1                        1006
#define IDC_PIC_LOGO                    1006
#define IDC_MAINTAB                     1006
#define IDC_TAB_TABLES                  1006
#define IDC_EDT_FILENAME                1007
#define IDC_PIC_LOGO2                   1007
#define IDC_BTN_BROWSE                  1008
#define IDC_SERVER_NAME                 1009
#define IDC_BTN_DISCONNECT              1009
#define IDC_PASSWORD                    1010
#define IDC_BTN_GO                      1010
#define IDC_USER_NAME2                  1011
#define IDC_BTN_CLEAR                   1011
#define IDC_BUTTON5                     1012
#define IDC_DATABASE_NAME               1012
#define IDC_BTN_CLROUTPUT               1012
#define IDC_BTN_LENGTH_INCREASE         1012
#define IDC_BTN_SELECT                  1013
#define IDC_BTN_UNDO                    1013
#define IDC_BTN_CLEAR2                  1013
#define IDC_BTN_PRINTTABLE              1014
#define IDC_BTN_SHOW_PASSWORD           1015
#define IDC_BTN_REDO                    1015
#define IDC_BTN_PRINTTABLE5             1015
#define IDC_SAVE_LOGIN                  1016
#define IDC_BTN_DISCONNECT2             1016
#define IDC_BTN_SCHEMA                  1016
#define IDC_BTN_REFRESHDBS              1016
#define IDC_BTN_PRINTTABLE2             1017
#define IDC_LIST_QUERY                  1018
#define IDC_BTN_DISCONNECT3             1019
#define IDC_BTN_PRINTTABLE4             1019
#define IDC_EXPORT                      1020
#define IDC_BTN_DELETETABLE             1021
#define IDC_BTN_PRINTTABLE3             1022
#define IDC_BTN_GO2                     1023
#define IDC_BTN_SELECTALL               1023
#define IDC_BTN_GO3                     1024
#define IDC_BTN_GO4                     1025
#define IDC_BTN_INSERT                  1025
#define IDC_BTN_GO5                     1026
#define IDC_BTN_UPDATERECORD            1026
#define IDC_COMBO_NMB_OF_ROWS           1027
#define IDC_BTN_GO6                     1028
#define IDC_BTN_DELETERECORD            1028
#define IDC_LIST_SEARCH                 1029
#define IDC_BUTTON1                     1030
#define IDC_BTN_FIRSTPAGE               1030
#define IDC_BTN_CREATEDB                1030
#define IDC_GO                          1030
#define IDC_BTN_HOME                    1030
#define IDC_BTN_GENERATE                1030
#define IDC_BTN_MONSTART                1030
#define IDC_BUTTON3                     1031
#define IDC_BTN_PREVPAGE                1031
#define IDC_BTN_DELETEDB                1031
#define IDC_BTN_MONSTART2               1031
#define IDC_BTN_MONCLEAR                1031
#define IDC_BTN_CLR_HIST                1031
#define IDC_STATIC_FILTER               1032
#define IDC_BTN_MONSTART3               1032
#define IDC_EDIT3                       1033
#define IDC_EDIT_GENPASSWORD            1033
#define IDC_TREE_STRUCTURE              1034
#define IDC_BTN_ENTER                   1035
#define IDC_BTN_COLLAPSE                1036
#define IDC_BTN_EXPAND                  1037
#define IDC_BTN_UPDATE                  1038
#define IDC_BTN_CLEARMSG                1039
#define IDC_RAD_CSV                     1040
#define IDC_RAD_XML                     1041
#define IDC_RAD_TEXT                    1042
#define IDC_BUTTON4                     1042
#define IDC_BTN_LASTPAGE                1042
#define IDC_BUTTON6                     1043
#define IDC_BTN_NEXTPAGE                1043
#define IDC_BTN_LENGTH_DECREASE         1043
#define IDC_CHECK1                      1044
#define IDC_RAD_HTML                    1044
#define IDC_AUTOSWITCH                  1044
#define IDC_CHECK_SHOWBINARY            1044
#define IDC_RAD_TSV                     1045
#define IDC_RICHEDIT_MSGS               1048
#define IDC_PROGRESS1                   1049
#define IDC_EXECPROGRESS                1049
#define IDC_PROGRESS_STRENGTH           1049
#define IDC_PROGRESS_INIT               1049
#define IDC_KINETIC                     1049
#define IDC_CMB_SEL_DB                  1050
#define IDC_POTENTIONAL                 1050
#define IDC_SYSLINK_SERVERINFO          1073
#define IDC_PIC_INFO                    1074
#define IDC_BUTTON2                     1078
#define IDC_BTN_FORWARD                 1078
#define IDC_COMBO2                      1079
#define IDC_CMB_DBS                     1079
#define IDC_CHECK_SHOWALL               1080
#define IDC_STAT_MAXPAGE                1082
#define IDC_INFO_PIC                    1083
#define IDC_BTN_REFACTOR                1086
#define IDC_BTNN_SELECT                 1088
#define IDC_COMBO_LANGUAGE              1089
#define IDC_LIST_TABLECREATE            1092
#define IDC_RICHEDIT22                  1094
#define IDC_TABLENAME                   1094
#define IDC_RICH_LINENUMBERER           1094
#define IDC_EDIT_ANGLE                  1094
#define IDC_RICHEDIT23                  1095
#define IDC_COLUMNS                     1095
#define IDC_RICH_SQL                    1095
#define IDC_EDIT_GRAVITY                1095
#define IDC_RICHEDIT24                  1096
#define IDC_COMMENTS                    1096
#define IDC_EDIT_MASS                   1096
#define IDC_LIST_COLUMNS                1097
#define IDC_RICHEDIT21                  1098
#define IDC_RICH_QUERYINFO              1098
#define IDC_STRINGCOUNTER               1098
#define IDC_SCROLLBAR2                  1105
#define IDC_LIST2                       1106
#define IDC_LIST_GUII                   1106
#define IDC_LIST_PLUGINS                1106
#define IDC_LIST3                       1107
#define IDC_PIC_MySQLGUI                1108
#define IDC_SYSLINK1                    1111
#define IDC_LIST_SERVER_INFO            1113
#define IDC_LIST_ENGINES                1114
#define IDC_LIST_VARS                   1115
#define IDC_LIST_CHARSETS               1116
#define IDC_LIST_DATABASES              1118
#define IDC_TOTAL                       1119
#define IDC_EDIT_VARSEARCH              1120
#define IDC_TAB_TITLE                   1121
#define IDC_EDIT_QUERY                  1122
#define IDC_STATIC_SELDB                1123
#define IDC_MFCBUTTON1                  1126
#define IDC_RADIO_NOPASSWORD            1128
#define IDC_RADIO_PASSWORD              1129
#define IDC_CONNCOLL                    1130
#define IDC_CHANGEPWD                   1131
#define IDC_CANCEL                      1132
#define IDC_EDIT_RETYPE                 1133
#define IDC_STATIC_STRENGTH             1134
#define IDC_BTN_UNSEL                   1135
#define IDC_PIC_TRAFFIC                 1136
#define IDC_PIC_CPU                     1137
#define IDC_PIC_CONNECTIONS             1138
#define IDC_PIC_PROCESSES               1139
#define IDC_RADIO1                      1141
#define IDC_RADIO2                      1142
#define IDC_CHECK3                      1143
#define IDC_BTN_REFRESH_VAR             1147
#define IDC_STATIC_ENTER                1148
#define IDC_STATIC_STRENGHT             1149
#define IDC_STATIC_RETYPE               1150
#define IDC_STATIC_GENERATE_PASSWORD    1151
#define IDC_CMB_VARS                    1152
#define IDC_EDIT_VARVALUE               1153
#define IDC_CMB_DATABASES               1154
#define IDC_EDIT_PLUGINSEARCH           1155
#define IDC_BTN_REFRESH_PLUGINS         1156
#define IDC_LIST_PLUGINSTAB             1157
#define IDC_EDIT_ENGINESSEARCH          1158
#define IDC_LIST_ENGINESTAB             1159
#define IDC_BTN_REFRESH_ENGINES         1160
#define IDC_EDIT_CHARSETSEARCH          1161
#define IDC_BTN_REFRESH_CHARSETS        1162
#define IDC_EDIT_SERVER_RUNNING_TIME    1163
#define IDC_STATIC_TRAFFIC_TITLE        1164
#define IDC_LIST_TRAFFIC                1165
#define IDC_LIST_CONNECTIONS            1166
#define IDC_BTN_TRAFFIC_UPDATE          1167
#define IDC_COMBO_STORAGE_ENGINE        1168
#define IDC_COLOR_FONT                  1169
#define IDC_FONT_SIZE                   1170
#define IDC_FONTCOMBO                   1174
#define IDC_STATIC_LOADING              1176
#define IDC_LOADING_PIC                 1177
#define IDC_MFCSHELLTREE1               1178
#define IDC_MFCSHELLLIST1               1179
#define IDC_MFCPROPERTYGRID1            1180
#define IDC_MFCMENUBUTTON1              1181
#define IDC_MFCMENUBUTTON2              1182
#define IDC_MFCMASKEDEDIT1              1183
#define IDC_MFCVSLISTBOX1               1185
#define IDC_MFCEDITBROWSE1              1186
#define IDC_MFCCOLORBUTTON1             1187
#define IDC_COMMAND1                    1188
#define IDC_NETADDRESS1                 1189
#define IDC_CUSTOM1                     1190
#define IDC_SPLIT1                      1191
#define IDC_COMBOBOXEX1                 1192
#define IDC_MONTHCALENDAR1              1193
#define IDC_RICH_GLOBALMESSAGES         1194
#define IDC_HOTKEY1                     1195
#define IDC_PENDULUM                    1196
#define IDC_START                       1197
#define IDC_RESTART                     1198
#define IDC_ADD_FORCE                   1199
#define IDC_DECREASE_FORCE              1200
#define IDC_EDIT_RESIST                 1201
#define IDC_BTN_MASS_INCREASE           1202
#define IDC_BTN_MASS_DECREASE           1203
#define IDC_EDIT_LENGTH                 1204
#define IDC_GRAPH                       1205
#define IDC_STATIC_POTENTIONAL          1206
#define IDC_STATIC_KINETIC              1207
#define IDC_LIST_STRUCTURE              1208
#define IDC_CMB_TBS                     1209
#define IDC_BTN_REFDB                   1210
#define IDC_BTN_REFDB2                  1211
#define IDC_BTN_REFTBL                  1211
#define IDC_BTN_HISTORY                 1211
#define IDC_LIST_HYSTORY                1212
#define IDC_BTN_SEL_HIST_REC            1213
#define IDC_BTN_OPN_HIST_FILE           1214
#define IDC_STATIC_SAVELOGINTITLE       1215
#define IDC_STATIC_SHOWPASSWORDTITLE    1216
#define ID_FILE_OPEN32771               32771
#define ID_EDIT_UNDO32772               32772
#define ID_EDIT_REDO32773               32773
#define ID_ABOUT_VERSIONANDCREDITS      32774
#define ID_CONNECTION_DISCONNECT        32775
#define ID_CONNECTION_CHECKCONNECTION   32776
#define ID_FILE_OPEN1                   32777
#define ID_FILE_OPEN32131               32778
#define ID_MENU_FILE_OPEN               32779
#define ID_MENU_OPEN                    32780
#define ID_CONNECTION_RECONNECT         32781
#define ID_FILE_EXPORTAS                32782
#define ID_EDIT_CUT32787                32787
#define ID_EDIT_COPY32788               32788
#define ID_PA                           32789
#define ID_EDIT_SELECTALL               32790
#define ID_HELP_MYSQLDOCUMENTATION      32791
#define ID_HELP_SERVERINFO              32792
#define ID_FILE_EXIT                    32793
#define ID_EDIT_PASTE32794              32794
#define ID_THEME                        32795
#define ID_THEME_DARK                   32796
#define ID_THEME_LIGHT                  32797
#define ID_FILE_OPENRECENT              32798
#define ID_FILE_SAVEAS                  32799
#define ID_FILE_EXPORT                  32800
#define ID_SERVER_EMPORTDATABASE        32801
#define ID_SERVER_EXPORTDATABASE        32802
#define ID_EDIT_SELECTALL32803          32803
#define ID_EDIT_123                     32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        210
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1216
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
