//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MFCDataBaseInterFace.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDD_MFCDATABASEINTERFACE_DIALOG 102
#define IDD_AUTH                        102
#define IDR_MAINFRAME                   128
#define IDD_MAIN                        130
#define IDR_MENU_MAIN                   132
#define IDD_EXPORT                      133
#define IDD_PROCEDURES                  138
#define IDD_DIALOG2                     139
#define IDD_FUNCTIONS                   139
#define IDD_ABOUT                       142
#define IDD_NEWDB                       144
#define IDD_TABLES                      146
#define IDD_QUERY                       148
#define IDD_DIALOG3                     149
#define IDD_RESULT                      149
#define IDD_HOME                        152
#define IDD_VARIABLES                   154
#define IDD_CHARSETS                    156
#define IDD_DATABASES                   158
#define IDD_CHANGEUSRPWD                161
#define IDD_CHANGEVARVALUE              163
#define IDD_STATUS                      165
#define IDD_STATUS_SERVER               165
#define IDD_STATUS_PROCESSES            167
#define IDD_STATUS_QSTATS               169
#define IDD_DIALOG1                     170
#define IDD_STATUS_MONITOR              170
#define IDB_BITMAP1                     173
#define IDB_PNG1                        174
#define IDB_PNG2                        175
#define IDR_IMAGE1                      176
#define IDB_PNG3                        177
#define IDB_PNG4                        178
#define IDB_PNG5                        179
#define IDC_EDIT1                       1000
#define IDC_EDT_OUTQTEXT                1000
#define IDC_EDIT_DESCRIPTION            1000
#define IDC_EDIT_CURRENTPAGE            1000
#define IDC_EDIT_DBNAME                 1000
#define IDC_EDIT2                       1001
#define IDC_EDIT_QTEXT                  1001
#define IDC_FILTER_DATABASES            1001
#define IDC_EDIT_ENTERPASSWORD          1001
#define IDC_BTN_CONNECT                 1002
#define IDC_BTN_EXIT                    1003
#define IDC_LIST1                       1004
#define IDC_COMBO1                      1005
#define IDC_SEL_TABLE                   1005
#define IDC_COMBO_CHARSET               1005
#define IDC_COLLATION                   1005
#define IDC_TAB1                        1006
#define IDC_PIC_LOGO                    1006
#define IDC_MAINTAB                     1006
#define IDC_EDT_FILENAME                1007
#define IDC_PIC_LOGO2                   1007
#define IDC_BTN_BROWSE                  1008
#define IDC_SERVER_NAME                 1009
#define IDC_BTN_DISCONNECT              1009
#define IDC_PASSWORD                    1010
#define IDC_BTN_GO                      1010
#define IDC_USER_NAME2                  1011
#define IDC_BTN_CLEAR                   1011
#define IDC_BUTTON5                     1012
#define IDC_DATABASE_NAME               1012
#define IDC_BTN_CLROUTPUT               1012
#define IDC_BTN_SELECT                  1013
#define IDC_BTN_UNDO                    1013
#define IDC_BTN_CLEAR2                  1013
#define IDC_BTN_PRINTTABLE              1014
#define IDC_BTN_SHOW_PASSWORD           1015
#define IDC_BTN_REDO                    1015
#define IDC_BTN_PRINTTABLE5             1015
#define IDC_SAVE_LOGIN                  1016
#define IDC_BTN_DISCONNECT2             1016
#define IDC_BTN_SCHEMA                  1016
#define IDC_BTN_REFRESHDBS              1016
#define IDC_BTN_PRINTTABLE2             1017
#define IDC_LIST_QUERY                  1018
#define IDC_BTN_DISCONNECT3             1019
#define IDC_BTN_PRINTTABLE4             1019
#define IDC_EXPORT                      1020
#define IDC_BTN_DELETETABLE             1021
#define IDC_BTN_PRINTTABLE3             1022
#define IDC_BTN_GO2                     1023
#define IDC_BTN_SELECTALL               1023
#define IDC_BTN_GO3                     1024
#define IDC_BTN_GO4                     1025
#define IDC_BTN_INSERT                  1025
#define IDC_BTN_GO5                     1026
#define IDC_BTN_UPDATERECORD            1026
#define IDC_COMBO_NMB_OF_ROWS           1027
#define IDC_BTN_GO6                     1028
#define IDC_BTN_DELETERECORD            1028
#define IDC_LIST_SEARCH                 1029
#define IDC_BUTTON1                     1030
#define IDC_BTN_FIRSTPAGE               1030
#define IDC_BTN_CREATEDB                1030
#define IDC_GO                          1030
#define IDC_BTN_HOME                    1030
#define IDC_BTN_GENERATE                1030
#define IDC_BTN_MONSTART                1030
#define IDC_BUTTON3                     1031
#define IDC_BTN_PREVPAGE                1031
#define IDC_BTN_DELETEDB                1031
#define IDC_STATIC_FILTER               1032
#define IDC_BTN_DELETEDB2               1032
#define IDC_EDIT3                       1033
#define IDC_EDIT_GENPASSWORD            1033
#define IDC_TREE_STRUCTURE              1034
#define IDC_BTN_ENTER                   1035
#define IDC_BTN_COLLAPSE                1036
#define IDC_BTN_EXPAND                  1037
#define IDC_BTN_UPDATE                  1038
#define IDC_BTN_CLEARMSG                1039
#define IDC_RAD_CSV                     1040
#define IDC_RAD_XML                     1041
#define IDC_RAD_TEXT                    1042
#define IDC_BUTTON4                     1042
#define IDC_BTN_LASTPAGE                1042
#define IDC_BUTTON6                     1043
#define IDC_BTN_NEXTPAGE                1043
#define IDC_CHECK1                      1044
#define IDC_RAD_HTML                    1044
#define IDC_AUTOSWITCH                  1044
#define IDC_CHECK_SHOWBINARY            1044
#define IDC_RAD_TSV                     1045
#define IDC_RICHEDIT_MSGS               1048
#define IDC_PROGRESS1                   1049
#define IDC_EXECPROGRESS                1049
#define IDC_PROGRESS_STRENGTH           1049
#define IDC_CMB_SEL_DB                  1050
#define IDC_SYSLINK_SERVERINFO          1073
#define IDC_PIC_INFO                    1074
#define IDC_BUTTON2                     1078
#define IDC_BTN_FORWARD                 1078
#define IDC_COMBO2                      1079
#define IDC_CHECK_SHOWALL               1080
#define IDC_STAT_MAXPAGE                1082
#define IDC_INFO_PIC                    1083
#define IDC_BTN_REFACTOR                1086
#define IDC_BTNN_SELECT                 1088
#define IDC_COMBO_LANGUAGE              1089
#define IDC_LIST_TABLECREATE            1092
#define IDC_RICHEDIT22                  1094
#define IDC_TABLENAME                   1094
#define IDC_RICH_LINENUMBERER           1094
#define IDC_RICHEDIT23                  1095
#define IDC_COLUMNS                     1095
#define IDC_RICH_SQL                    1095
#define IDC_RICHEDIT24                  1096
#define IDC_COMMENTS                    1096
#define IDC_LIST_COLUMNS                1097
#define IDC_RICHEDIT21                  1098
#define IDC_RICH_QUERYINFO              1098
#define IDC_STRINGCOUNTER               1098
#define IDC_SCROLLBAR2                  1105
#define IDC_LIST2                       1106
#define IDC_LIST_GUII                   1106
#define IDC_LIST_PLUGINS                1106
#define IDC_LIST3                       1107
#define IDC_PIC_MySQLGUI                1108
#define IDC_SYSLINK1                    1111
#define IDC_LIST_SERVER_INFO            1113
#define IDC_LIST_ENGINES                1114
#define IDC_LIST_VARS                   1115
#define IDC_LIST_CHARSETS               1116
#define IDC_LIST_DATABASES              1118
#define IDC_TOTAL                       1119
#define IDC_EDIT_VARSEARCH              1120
#define IDC_TAB_TITLE                   1121
#define IDC_EDIT_QUERY                  1122
#define IDC_STATIC_SELDB                1123
#define IDC_MFCBUTTON1                  1126
#define IDC_RADIO_NOPASSWORD            1128
#define IDC_RADIO_PASSWORD              1129
#define IDC_CONNCOLL                    1130
#define IDC_CHANGEPWD                   1131
#define IDC_CANCEL                      1132
#define IDC_EDIT_RETYPE                 1133
#define IDC_STATIC_STRENGTH             1134
#define IDC_BTN_UNSEL                   1135
#define IDC_PIC_TRAFFIC                 1136
#define IDC_PIC_CPU                     1137
#define IDC_PIC_CONNECTIONS             1138
#define IDC_PIC_PROCESSES               1139
#define IDC_RADIO1                      1141
#define IDC_RADIO2                      1142
#define IDC_CHECK3                      1143
#define IDC_BTN_REFRESH_VAR             1147
#define IDC_STATIC_ENTER                1148
#define IDC_STATIC_STRENGHT             1149
#define IDC_STATIC_RETYPE               1150
#define IDC_STATIC_GENERATE_PASSWORD    1151
#define IDC_CMB_VARS                    1152
#define IDC_EDIT_VARVALUE               1153
#define IDC_CMB_DATABASES               1154
#define ID_FILE_OPEN32771               32771
#define ID_EDIT_UNDO32772               32772
#define ID_EDIT_REDO32773               32773
#define ID_ABOUT_VERSIONANDCREDITS      32774
#define ID_CONNECTION_DISCONNECT        32775
#define ID_CONNECTION_CHECKCONNECTION   32776
#define ID_FILE_OPEN1                   32777
#define ID_FILE_OPEN32131               32778
#define ID_MENU_FILE_OPEN               32779
#define ID_MENU_OPEN                    32780
#define ID_CONNECTION_RECONNECT         32781
#define ID_FILE_EXPORTAS                32782
#define ID_EDIT_CUT32787                32787
#define ID_EDIT_COPY32788               32788
#define ID_PA                           32789
#define ID_EDIT_SELECTALL               32790
#define ID_HELP_MYSQLDOCUMENTATION      32791
#define ID_HELP_SERVERINFO              32792
#define ID_FILE_EXIT                    32793
#define ID_EDIT_PASTE32794              32794
#define ID_THEME                        32795
#define ID_THEME_DARK                   32796
#define ID_THEME_LIGHT                  32797
#define ID_FILE_OPENRECENT              32798
#define ID_FILE_SAVEAS                  32799
#define ID_FILE_EXPORT                  32800
#define ID_SERVER_EMPORTDATABASE        32801
#define ID_SERVER_EXPORTDATABASE        32802
#define ID_EDIT_SELECTALL32803          32803
#define ID_EDIT_123                     32804

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        180
#define _APS_NEXT_COMMAND_VALUE         32805
#define _APS_NEXT_CONTROL_VALUE         1155
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
